IF OBJECT_ID(N'civicrm__case') IS NOT NULL
    DROP TABLE civicrm__case

IF OBJECT_ID(N'civicrm__contact') IS NOT NULL
    DROP TABLE civicrm__contact

DECLARE @SQL NVARCHAR(MAX)
DECLARE @table_name VARCHAR(255)

DECLARE TABLE_CURSOR CURSOR
    LOCAL STATIC READ_ONLY FORWARD_ONLY
FOR
SELECT t.TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES t 
WHERE t.TABLE_NAME LIKE 'civicrm_value_%'

OPEN TABLE_CURSOR
FETCH NEXT FROM TABLE_CURSOR INTO @table_name
WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT 'Dropping ' + @table_name

    SELECT @SQL = 'DROP TABLE ' + QUOTENAME(@table_name);
    EXEC sp_executesql @SQL

    FETCH NEXT FROM TABLE_CURSOR INTO @table_name
END
CLOSE TABLE_CURSOR
DEALLOCATE TABLE_CURSOR
