IF OBJECT_ID(N'cfg_participant_identifier_type') IS NULL
BEGIN
	CREATE TABLE cfg_participant_identifier_type (
		id int IDENTITY(1,1) NOT NULL PRIMARY KEY,
		name nvarchar(500),
		INDEX idx__cfg_participant_identifier_type__name (name),
	);

	-- NHS IDs
	INSERT INTO cfg_participant_identifier_type (name) VALUES
		(N'UHL_NUMBER'),
		(N'uhl_system_number'),
		(N'nhs_number');

	-- Study IDs
	INSERT INTO cfg_participant_identifier_type (name) VALUES
		(N'4d_pharma_id'),
		(N'alleviate_id'),
		(N'amaze_id'),
		(N'az_mahale_id'),
		(N'AS_PROGRESSION_ID'),
		(N'beat_sa_id'),
		(N'Benrex_id'),
		(N'BIORESOURCE_ID'),
		(N'BIORESOURCE_LEGACY_ID'),
		(N'BIOSTAT_ID'),
		(N'BME_COVID_ID'),
		(N'bpf_gild_id'),
		(N'BRAVE_ID'),
		(N'BREATHE_DEEP_ID'),
		(N'BRICCS_ID'),
		(N'CARDIOMET_ID'),
		(N'CARLOTA_ID'),
		(N'CARMER_BREATH_ID'),
		(N'cascade_id'),
		(N'CIA_ID'),
		(N'CMR_VS_CT_ID'),
		(N'CHESTY_ID'),
		(N'CHESTY_REDCAP_ID'),
		(N'chinook_id'),
		(N'COHERE_ID'),
		(N'COPD_COVID_19_ID'),
		(N'copd_st2op_id'),
		(N'copd_had_id'),
		(N'copd_help_id'),
		(N'COSMIC_ID'),
		(N'course_id'),
		(N'covid_heart_id'),
		(N'CTO_ID'),
		(N'CVLPRIT_ID'),
		(N'CVLPRIT_LOCAL_ID'),
		(N'ddtbd_id'),
		(N'DESMOND_ID'),
		(N'DHF_ID'),
		(N'DIASTOLIC_ID'),
		(N'DISCORDANCE_ID'),
		(N'DREAM_ID'),
		(N'EDEN_ID'),
		(N'EDIFY_ID'),
		(N'ELASTIC_AS_ID'),
		(N'EMBER_ID'),
		(N'EMMACE4_ID'),
		(N'EPIGENE1_ID'),
		(N'event_id'),
		(N'EXTEND_ID'),
		(N'FAST_ID'),
		(N'FOAMI_ID'),
		(N'genentech_id'),
		(N'GENVASC_ID'),
		(N'GLOBAL_VIEWS_ID'),
		(N'GO_DCM_ID'),
		(N'gossamer_id'),
		(N'GRAPHIC_LAB_ID'),
		(N'GRAPHIC2_ID'),
		(N'HAD_ID'),
		(N'ILD_ID'),
		(N'INDAPAMIDE_ID'),
		(N'INTERFIELD_ID'),
		(N'INTERVAL_ID'),
		(N'ironman_id'),
		(N'LENTEN_ID'),
		(N'LIMB_ID'),
		(N'MARI_ID'),
		(N'MEIRU_ID'),
		(N'MEL_ID'),
		(N'mesos_lcm_id'),
		(N'MI_ECMO_ID'),
		(N'MINERVA_ID'),
		(N'MVO_ID'),
		(N'MULTI_MORBID_PRIORITIES_ID'),
		(N'NON_ADHERENCE_ID'),
		(N'National_Bioresource_id'),
		(N'omics_id'),
		(N'ORFAN_ID'),
		(N'PILOT_ID'),
		(N'ponente_id'),
		(N'PREDICT_ID'),
		(N'pre_op_energy_id'),
		(N'PRESTIGE_ID'),
		(N'PREECLAMPSIA_ID'),
		(N'PRIMID_ID'),
		(N'p_vect_id'),
		(N'rasp_id'),
		(N'RAPID_NSTEMI_ID'),
		(N'REST_ID'),
		(N'SALT_ID'),
		(N'SCAD_CAE_ID'),
		(N'SCAD_ID'),
		(N'SCAD_LOCAL_ID'),
		(N'SCAD_REG_ID'),
		(N'SCAD_SURVEY_ID'),
		(N'SKOPE_ID'),
		(N'SPACE_FOR_COPD_ID'),
		(N'SPIRAL_ID'),
		(N'tmao_id'),
		(N'thermoplasty_basal_id'),
		(N'UPFOR5_ID'),
		(N'VASCEGENS_ID'),
		(N'yakult_id'),
		(N'yoga_id'),
		(N'novo5k_id'),
		(N'mmq_id'),
		(N'foot_and_ankle_id'),
		(N'cmr_vs_ctffr_id'),
		(N'cmr_vs_ctffr_redcap_id'),
		(N'chablis_id'),
		(N'scad_ct_id'),
		(N'shocc_id'),
		(N'mri_asymptomatic_as_id'),
		(N'mri_uspio_id'),
		(N'crispy_id'),
		(N'target_id'),
		(N'reset_id'),
		(N'easy_as_id'),
		(N'ldc_volunteer_id'),
		(N'covid_risk_perception_id'),
		(N'covid_care_home_chronic_disease_id'),
		(N'slimcard_id'),
		(N'covid_vaccine_hesitancy_id'),
		(N'obesity_uk_ppi_id'),
		(N'ultimate_id'),
		(N'valcard_id'),
		(N'ukags_id'),
		(N'DISCORDANCE_ANONYMOUS_IMAGE_ID');

	-- CiviCRM IDs
	INSERT INTO cfg_participant_identifier_type (name) VALUES
		(N'CiviCRM Case ID'),
		(N'CiviCRM Contact ID');

	-- OpenSpecimen
	INSERT INTO cfg_participant_identifier_type (name) VALUES
		(N'OpenSpecimen Participant ID');

END
