SET NOCOUNT ON;
DECLARE @OPENQUERY NVARCHAR(MAX)
DECLARE @SQL NVARCHAR(MAX)
DECLARE @table_name VARCHAR(255)
DECLARE @column_name VARCHAR(255)

DECLARE TABLE_CURSOR CURSOR
    LOCAL STATIC READ_ONLY FORWARD_ONLY
FOR 
SELECT
    TABLE_NAME,
    COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE DATA_TYPE LIKE '%text%'

OPEN TABLE_CURSOR
FETCH NEXT FROM TABLE_CURSOR INTO @table_name, @column_name
WHILE @@FETCH_STATUS = 0
BEGIN

    SELECT @SQL = 'ALTER TABLE ' + @table_name + ' ALTER COLUMN ' + @column_name + ' VARCHAR(MAX)'

    EXEC sp_executesql @SQL

    FETCH NEXT FROM TABLE_CURSOR INTO @table_name, @column_name
END
CLOSE TABLE_CURSOR
DEALLOCATE TABLE_CURSOR
